### ISSUE TITLE
Add filter functionality to Lesson Builder

### ISSUE THREAD

**Issue by daniellerad** [radcampaign/pulitzer2016#141] opened 2016-11-23 19:09 UTC
The Lesson Builder should have the same search/filter functionality as the Reporting page, except for removing the irrelevant fields (Publication, Media) and replacing them with relevant fields (Level/Audience, Subject).

**Comment by xaqrox** [comment] 2017-01-27 16:11
Duplicate of #112

**Closed by xaqrox** 2017-01-27 16:11 UTC
